language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
    - composer self-update
    - composer --version
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php php-cs-fixer.phar --version; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar; fi

install:
    - COMPOSER_ROOT_VERSION=dev-master COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-source $COMPOSER_FLAGS

script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php php-cs-fixer.phar fix --dry-run -v; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then bin/phpunit --coverage-clover build/logs/clover.xml; fi
    - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then bin/phpunit; fi

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php php-coveralls.phar -v; fi
